# Generated by Django 3.2.8 on 2021-10-27 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_id', models.IntegerField(max_length=100)),
                ('state_code', models.CharField(max_length=100, null=True)),
                ('country_id', models.IntegerField(max_length=100, null=True)),
                ('country_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('wikiDataId', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Select Country')),
                ('phonecode', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.IntegerField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('state_code', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email addr')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
